BEGIN;

-- 1. Choose your top-3 favorite movies and add them to the 'film' table (dif release_year, category, )
-- Using RETURNING to capture IDs for subsequent operations (use schema name before table, 
--not hardcode use select before inserting lang id-s)
-- 4.99, 9.99 and 19.99 and rental durations with 1, 2 and 3 weeks 


WITH new_films AS (                   -- CTE makes my data reusable
  INSERT INTO public.film (
    title,
    description,
    release_year,
    language_id,
    rental_duration,
    rental_rate,
    length,
    replacement_cost,
    rating,
    special_features,
    last_update
  )
  SELECT 
    f.title,
    f.description,
    f.release_year,
    l.language_id,                     -- I select it though join in roder to avoid hardociding, and inserting the wrong ID
    f.rental_duration,
    f.rental_rate,
    f.length,
    f.replacement_cost,
    f.rating::mpaa_rating,
    string_to_array(f.special_features, ',')::text[],
    CURRENT_DATE
  FROM (
    VALUES
    ('Pride and Prejudice',
     'Sparks fly when Elizabeth Bennet meets Mr. Darcy.',
     2005, 'English', 21, 19.99, 127, 19.99, 'PG', 'Commentaries,Deleted Scenes'),

    ('Jane Eyre',
     'A governess falls in love with her mysterious employer.',
     2011, 'English', 14, 9.99, 120, 19.99, 'PG-13', 'Behind the Scenes'),

    ('Dancer in the Dark',
     'An immigrant struggles to survive in America.',
     2000, 'English', 7, 4.99, 140, 19.99, 'R', 'Trailers')

  ) AS f(title, description, release_year, language_name, rental_duration,
         rental_rate, length, replacement_cost, rating, special_features)   --VALUES (...) AS f(...) creates a temporary table with columns and rows, 
                                                                             -- also lets me get the colum names 
  JOIN public.language l                             -- I join to insert by select into instead of hardcoding
    ON LOWER(l.name) = LOWER(f.language_name)

  WHERE NOT EXISTS (                                 --- this ensures that no duplicates are created
    SELECT 1                                         -- and the titles that I insert are not already inserted in the film table 
    FROM public.film existing                         -- THUS ensures uniqueness
    WHERE LOWER(existing.title) = LOWER(f.title)
  )

  Returning *            -- returns the rows that I have just inserted (in other cases the rows that I have deleted or updated)
)                        -- no extra query neeeded plus I can also see the ID that sql have autogenerated 

SELECT * FROM new_films;

COMMIT;


--Comment about Begin - Commit
--- In my case I just have one insert statement which is already atomic by itself - so if one of the values
-- does not match the column datatype I am inserting it into (or if I have any
-- other mechanic problem) the statement fails and none of the values 
-- will get inserted.
-- however if I had several insert into statements than begin and commit would have been really helpful 
-- cause insert into would directly input the partial data  even if one of the 'insert into' statements 
-- have failed while begin - commit/rollback groups all the statemnts into 
-- one transaction and  gives me the ability to think after running a query
-- whether I want my changes to get saved or to rollback - this ensures the consistency





--- 2. Fill in rental rates with 4.99, 9.99 and 19.99 and rental durations with 1, 2 and 3 weeks respectively.
-- IMPORTANT
--- not fully understood whether I should have updated data here or inserted this info along the other details in the prev query
-- in the previous subtask I provided how I would have inserted them here I write the update version
BEGIN;



-- CTE to select films dynamically (case-insensitive)
WITH films_to_update AS (
    SELECT f.film_id, f.title
    FROM public.film f
    WHERE LOWER(f.title) IN (
        LOWER('Pride and Prejudice'),
        LOWER('Jane Eyre'),
        LOWER('Dancer in the Dark')
    )
)

UPDATE public.film f
SET 
    rental_rate = CASE 
        WHEN LOWER(f.title) = LOWER('Pride and Prejudice') THEN 19.99
        WHEN LOWER(f.title) = LOWER('Jane Eyre') THEN 9.99
        WHEN LOWER(f.title) = LOWER('Dancer in the Dark') THEN 4.99
        ELSE f.rental_rate
    END,
    rental_duration = CASE 
        WHEN LOWER(f.title) = LOWER('Pride and Prejudice') THEN 21
        WHEN LOWER(f.title) = LOWER('Jane Eyre') THEN 14
        WHEN LOWER(f.title) = LOWER('Dancer in the Dark') THEN 7
        ELSE f.rental_duration
    END,
    last_update = CURRENT_DATE
FROM films_to_update fu
WHERE f.film_id = fu.film_id

RETURNING *;   


-- verifying before commit
SELECT film_id, title, rental_rate, rental_duration, last_update
FROM public.film
WHERE LOWER(title) IN (
    LOWER('Pride and Prejudice'),
    LOWER('Jane Eyre'),
    LOWER('Dancer in the Dark')
);

COMMIT;


-- 3. Add the actors who play leading roles in your favorite movies to the 'actor' and 'film_actor' tables 


BEGIN;

-- Insert actors
WITH new_actors AS (
    INSERT INTO public.actor (first_name, last_name, last_update)
    SELECT a.first_name, a.last_name, CURRENT_DATE
    FROM (VALUES
        ('Keira', 'Knightley'),
        ('Matthew', 'Macfadyen'),
        ('Mia', 'Wasikowska'),
        ('Michael', 'Fassbender'),
        ('Björk', ''),
        ('Catherine', 'Deneuve')
    ) AS a(first_name, last_name)
    WHERE NOT EXISTS (
        SELECT 1
        FROM public.actor existing
        WHERE LOWER(existing.first_name) = LOWER(a.first_name)
          AND LOWER(existing.last_name) = LOWER(a.last_name)
    )
    RETURNING actor_id, first_name, last_name
)

SELECT * FROM new_actors;

-- Link actors to films
INSERT INTO public.film_actor (actor_id, film_id, last_update)
SELECT a.actor_id, f.film_id, CURRENT_DATE
FROM public.actor a
JOIN public.film f ON (
    (LOWER(a.first_name) = 'keira' AND LOWER(a.last_name) = 'knightley' AND LOWER(f.title) = 'pride and prejudice') OR
    (LOWER(a.first_name) = 'matthew' AND LOWER(a.last_name) = 'macfadyen' AND LOWER(f.title) = 'pride and prejudice') OR
    (LOWER(a.first_name) = 'mia' AND LOWER(a.last_name) = 'wasikowska' AND LOWER(f.title) = 'jane eyre') OR
    (LOWER(a.first_name) = 'michael' AND LOWER(a.last_name) = 'fassbender' AND LOWER(f.title) = 'jane eyre') OR
    (LOWER(a.first_name) = 'björk' AND LOWER(a.last_name) = '' AND LOWER(f.title) = 'dancer in the dark') OR
    (LOWER(a.first_name) = 'catherine' AND LOWER(a.last_name) = 'deneuve' AND LOWER(f.title) = 'dancer in the dark')
)
WHERE NOT EXISTS (
    SELECT 1
    FROM public.film_actor fa
    WHERE fa.actor_id = a.actor_id
      AND fa.film_id = f.film_id
)
RETURNING actor_id, film_id;

COMMIT;


-- 4. add fav movies to the store inventory 

BEGIN;

WITH target_films AS (
    SELECT film_id
    FROM public.film
    WHERE title IN (
        'Pride and Prejudice',
        'Jane Eyre',
        'Dancer in the Dark'
    )
),
selected_store AS (
    SELECT store_id
    FROM public.store
    ORDER BY RANDOM()
    LIMIT 1
)

INSERT INTO inventory (film_id, store_id, last_update)
SELECT 
    tf.film_id,
    ss.store_id,
    CURRENT_TIMESTAMP
FROM target_films tf
CROSS JOIN selected_store ss
WHERE NOT EXISTS (
    SELECT 1
    FROM inventory i
    WHERE i.film_id = tf.film_id
      AND i.store_id = ss.store_id
)
RETURNING *;

COMMIT;

-- 6. Alter any existing customer in the database with at least 43 rental and 43 payment records. 
--    Change their personal data to yours (first name, last name, address, etc.). 
--    You can use any existing address from the "address" table.

BEGIN;

-- 1 Identify eligible customer
WITH eligible_customer AS (
    SELECT c.customer_id
    FROM public.customer c
    JOIN public.rental r ON r.customer_id = c.customer_id
    JOIN public.payment p ON p.customer_id = c.customer_id
    GROUP BY c.customer_id
    HAVING COUNT(DISTINCT r.rental_id) >= 43
       AND COUNT(DISTINCT p.payment_id) >= 43
    LIMIT 1
)

-- Step 2: Update customer data
UPDATE public.customer c
SET 
    first_name = 'Nino',
    last_name = 'Sarishvili',
    email = 'nino.sarishvili@example.com',
    address_id = (
        SELECT address_id 
        FROM public.address 
        LIMIT 1
    ),
    last_update = CURRENT_DATE
WHERE c.customer_id IN (SELECT customer_id FROM eligible_customer)

RETURNING c.customer_id, c.first_name, c.last_name, c.email, c.address_id;

COMMIT;

--7 Remove any records related to you (as a customer) from all tables except 'Customer' and 'Inventory'
begin;


with me as (
    SELECT customer_id
    FROM public.customer
    WHERE LOWER(first_name) = 'nino'
      AND LOWER(last_name) = 'sarishvili'
), 

DELETE FROM public.payment p
WHERE p.customer_id IN (SELECT customer_id FROM target_customer)
RETURNING p.payment_id;

DELETE FROM public.rental r
WHERE r.customer_id IN (SELECT customer_id FROM target_customer)
RETURNING r.rental_id;

commit;


--8 Rent you favorite movies from the store they are in and pay for them


BEGIN;

--1 Identifying mysekf
WITH target_customer AS (
    SELECT customer_id
    FROM public.customer
    WHERE LOWER(first_name) = 'nino'
      AND LOWER(last_name) = 'sarishvili'
),

--2 Getting films I added earlier
target_films AS (
    SELECT film_id
    FROM public.film
    WHERE LOWER(title) IN (
        'pride and prejudice',
        'jane eyre',
        'dancer in the dark'
    )
),

-- 3 finding available inventory
available_inventory AS (
    SELECT i.inventory_id, i.store_id
    FROM public.inventory i
    JOIN target_films f ON f.film_id = i.film_id
    WHERE NOT EXISTS (
        SELECT 1
        FROM public.rental r
        WHERE r.inventory_id = i.inventory_id
          AND r.return_date IS NULL
    )
    LIMIT 3
),

-- 4 Inserting rentals
new_rentals AS (
    INSERT INTO public.rental (
        rental_date,
        inventory_id,
        customer_id,
        return_date,
        staff_id,
        last_update
    )
    SELECT 
        CURRENT_DATE,
        ai.inventory_id,
        tc.customer_id,
        CURRENT_DATE + INTERVAL '3 days',
        (SELECT staff_id FROM public.staff LIMIT 1),
        CURRENT_DATE
    FROM available_inventory ai
    CROSS JOIN target_customer tc
    WHERE NOT EXISTS (
        SELECT 1
        FROM public.rental r
        WHERE r.inventory_id = ai.inventory_id
          AND r.customer_id = tc.customer_id
    )
    RETURNING rental_id, inventory_id, customer_id
)

-- 5 Inserting payments
INSERT INTO public.payment (
    customer_id,
    staff_id,
    rental_id,
    amount,
    payment_date
)
SELECT 
    nr.customer_id,
    (SELECT staff_id FROM public.staff LIMIT 1),
    nr.rental_id,
    4.99,
    DATE '2017-01-15'   -- safe partition date
FROM new_rentals nr
WHERE NOT EXISTS (
    SELECT 1
    FROM public.payment p
    WHERE p.rental_id = nr.rental_id
)
RETURNING payment_id, rental_id, amount;

COMMIT;

